// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // PKCE is the recommended flow for SPAs — it prevents token interception via
    // the URL hash and correctly handles the ?code= callback that Supabase sends
    // after OAuth. Without this, the default implicit flow stores tokens in the
    // URL hash, which some browser/proxy environments strip before the JS runs.
    flowType: "pkce",
    // Ensure the client detects and exchanges the ?code= in the URL on OAuth return.
    detectSessionInUrl: true,
  }
});